# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=web.models.uploadImage(prefix=b'p'))),
                ('name', models.CharField(max_length=200)),
                ('beginning', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('url', models.CharField(blank=True, max_length=500)),
                ('source_code_url', models.CharField(blank=True, max_length=500)),
                ('screenshot1', models.ImageField(null=True, upload_to=web.models.uploadImage(prefix=b'p/s'))),
                ('screenshot2', models.ImageField(null=True, upload_to=web.models.uploadImage(prefix=b'p/s'))),
                ('screenshot3', models.ImageField(null=True, upload_to=web.models.uploadImage(prefix=b'p/s'))),
                ('small', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=web.models.uploadImage(prefix=b's'))),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('importance', models.PositiveIntegerField(default=1)),
                ('small', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='stats',
            field=models.ManyToManyField(to='web.Stat'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='web.Tag'),
        ),
    ]
