# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('importance', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.uploadImage(prefix=b'p')),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot1',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.uploadImage(prefix=b'p/s')),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.uploadImage(prefix=b'p/s')),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot3',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.uploadImage(prefix=b'p/s')),
        ),
    ]
