# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161202_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='importance',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='tags',
            field=models.ManyToManyField(to='web.SocialTag'),
        ),
    ]
